# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='download_name',
            field=models.CharField(default='report.csv', max_length=100),
        ),
    ]
