# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_download_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='d3_file_name',
            field=models.CharField(default='new_users.js', max_length=100),
        ),
    ]
