# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_download_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='d3_file_name',
            field=models.CharField(default='.js', max_length=100),
        ),
    ]
