# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_broadcastemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastemail',
            options={'verbose_name': 'Broadcast Email', 'verbose_name_plural': 'Broadcast Emails'},
        ),
        migrations.AddField(
            model_name='report',
            name='description_html',
            field=models.TextField(default='', editable=False),
        ),
    ]
