# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 23:56
from __future__ import unicode_literals

from django.db import migrations


def port_description_to_html(apps, schema_editor):
    reports = apps.get_model("reports", "Report")
    for report in reports.objects.all():
        if not report.description_html and report.description:
            report.description_html = report.description
            report.save()


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0011_auto_20161124_1638'),
    ]

    operations = [
        migrations.RunPython(port_description_to_html)
    ]
