# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20161205_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudallocated',
            old_name='other',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='cloudused',
            old_name='other',
            new_name='services',
        ),
    ]
