# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20161205_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPrivateCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(help_text='The date on which the values were calculated')),
                ('project_id', models.CharField(help_text='The project ID', max_length=32)),
                ('vcpus', models.IntegerField(help_text='The project VCPU count on the date')),
                ('instances', models.IntegerField(help_text='The project instance count on the date')),
                ('display_name', models.CharField(help_text="The project's formal name", max_length=64)),
                ('organization', models.CharField(help_text='The organization the project belongs to', max_length=255)),
            ],
            options={
                'db_table': 'cloud_private_cell',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cloudprivatecell',
            unique_together=set([('date', 'project_id')]),
        ),
    ]
