# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20161208_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudprivatecell',
            name='faculty',
            field=models.CharField(default='Unknown', help_text='The faculty the project belongs to', max_length=10),
        ),
    ]
