# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_cloudquarterly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudQuarterlyUsage',
            fields=[
                ('quarter_start_date', models.TextField(help_text='The quarter start date', primary_key=True, serialize=False, unique=True)),
                ('quarter_end_date', models.TextField(help_text='The quarter end date', unique=True)),
                ('projects_active', models.IntegerField(help_text='The total number of active projects')),
                ('uom_projects_active', models.IntegerField(help_text='The number of UoM projects active')),
                ('uom_participation', models.IntegerField(help_text='The number of projects active with UoM users')),
                ('uom_users_active', models.IntegerField(help_text='The total number of UoM users active')),
            ],
            options={
                'db_table': 'cloud_quarterly_usage',
            },
        ),
    ]
