# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:05
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_cloudquarterlyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudquarterlyusage',
            name='all_uom_projects_active',
            field=models.IntegerField(default=0, help_text='The count of all UoM projects active'),
        ),
        migrations.AlterField(
            model_name='cloudquarterlyusage',
            name='date',
            field=models.TextField(
                default=django.utils.timezone.now,
                help_text='The quarter end date',
                primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cloudquarterlyusage',
            name='projects_active',
            field=models.IntegerField(help_text='The total count of active projects'),
        ),
        migrations.AlterField(
            model_name='cloudquarterlyusage',
            name='uom_participation',
            field=models.IntegerField(default=0, help_text='The count of projects active with UoM users'),
        ),
        migrations.AlterField(
            model_name='cloudquarterlyusage',
            name='uom_projects_active',
            field=models.IntegerField(default=0, help_text='The count of approved UoM projects active'),
        ),
        migrations.AlterField(
            model_name='cloudquarterlyusage',
            name='uom_users_active',
            field=models.IntegerField(default=0, help_text='The total count of UoM users active'),
        ),
    ]
