# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20170116_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudquarterlyusage',
            name='all_users_active',
            field=models.IntegerField(default=0, help_text='The count of all users active'),
        ),
        migrations.AlterField(
            model_name='cloudquarterlyusage',
            name='date',
            field=models.TextField(default=datetime.datetime(2017, 1, 16, 3, 10, 11, 543706, tzinfo=utc), help_text='The quarter end date', primary_key=True, serialize=False, unique=True),
        ),
    ]
