# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20170116_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProjectFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('contact_email', models.CharField(blank=True, max_length=75, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('faculty_abbreviation', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'cloud_project_faculty',
                'managed': False,
            },
        ),
    ]
