# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_auto_20170503_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudprojectfaculty',
            options={},
        ),
    ]
