# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20170503_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudprojectfaculty',
            name='id',
        ),
        migrations.AddField(
            model_name='cloudprojectfaculty',
            name='faculties',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='project_id',
            field=models.TextField(default='0', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
