# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_auto_20170518_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='allocated_faculty',
            field=models.CharField(blank=True, help_text='The faculty we have decided the project belongs to', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='chief_investigator',
            field=models.CharField(blank=True, help_text="The nominated chief investigator's email", max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='contact_email',
            field=models.CharField(blank=True, help_text="The applicant's email", max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='for_code',
            field=models.CharField(blank=True, help_text='The highest weighted FOR code', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='name',
            field=models.CharField(blank=True, help_text='The project name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cloudprojectfaculty',
            name='project_id',
            field=models.TextField(default='0', help_text='The projects ID', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
