# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20170518_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudprojectfaculty',
            name='name',
        ),
        migrations.AddField(
            model_name='cloudprojectfaculty',
            name='description',
            field=models.CharField(blank=True, help_text='The project description', max_length=64, null=True),
        ),
    ]
