# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_auto_20170608_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudQuarterlyCoreHours',
            fields=[
                ('date', models.TextField(help_text='The date on which the values in the row were calculated', primary_key=True, serialize=False, unique=True)),
                ('foa', models.IntegerField(db_column='FoA')),
                ('vas', models.IntegerField(db_column='VAS')),
                ('fbe', models.IntegerField(db_column='FBE')),
                ('mse', models.IntegerField(db_column='MSE')),
                ('mgse', models.IntegerField(db_column='MGSE')),
                ('mdhs', models.IntegerField(db_column='MDHS')),
                ('fos', models.IntegerField(db_column='FoS')),
                ('abp', models.IntegerField(db_column='ABP')),
                ('mls', models.IntegerField(db_column='MLS')),
                ('vcamcm', models.IntegerField(db_column='VCAMCM')),
                ('services', models.IntegerField(db_column='Other')),
                ('unknown', models.IntegerField(db_column='Unknown')),
            ],
            options={
                'db_table': 'cloud_quarterly_core_hours',
            },
        ),
    ]
